name = "pimx-eltex"
main = ".open-next/worker.js"
compatibility_date = "2026-09-13"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "pimx-eltex-db"
database_id = "1dbe35e8-2c2e-4ff4-9550-f4b8eda11567"
migrations_dir = "drizzle"
