"use client";

import { Activity, Ban, BarChart3, Clock3, Code2, Eye, FileText, Globe2, LayoutDashboard, LoaderCircle, MapPinned, MessageSquare, MonitorSmartphone, Pencil, Plus, ShieldCheck, Trash2, UsersRound, X } from "lucide-react";
import { useState } from "react";
import { EpisodeEditor, type EpisodeInitialData } from "./episode-editor";
import { UiSelect } from "./ui-select";
import { ConfirmDialog } from "./confirm-dialog";

type AdminUser = { id: string; name: string; age: number | null; email: string; country: string; status: string };
type AdminPost = { id: string; title: string; slug: string; status: string };
type AdminComment = { id: string; content: string; author: string; post: string };
type AdminProject = { id: string; title: string; slug: string; status: string; previewUrl: string; downloadUrl: string };
type Analytics = { totalViews: number; uniqueVisitors: number; totalDurationSeconds: number; countries: { label: string; value: number }[]; devices: { label: string; value: number }[]; browsers: { label: string; value: number }[]; paths: { label: string; value: number }[] };
type UserDetails = { member: AdminUser & { username: string; role: string; emailVerifiedAt: string | null; lastLoginAt: string | null; createdAt: string }; totals: { visits: number; durationSeconds: number }; devices: { id: string; countryCode: string | null; city: string | null; region: string | null; deviceType: string | null; operatingSystem: string | null; browser: string | null; ipAddress: string; visitCount: number; totalDurationSeconds: number; createdAt: string; lastSeenAt: string }[]; sessions: { id: string; countryCode: string | null; city: string | null; region: string | null; deviceType: string | null; operatingSystem: string | null; browser: string | null; ipAddress: string; createdAt: string; lastSeenAt: string; expiresAt: string }[]; recentVisits: { id: string; path: string; countryCode: string | null; city: string | null; deviceType: string | null; browser: string | null; durationSeconds: number; createdAt: string }[] };
type DeleteTarget = { kind: "episode" | "project" | "comment" | "member"; id: string; name: string };
type Tab = "overview" | "analytics" | "episodes" | "projects" | "comments" | "users";

const publishingOptions = [
  { value: "draft", label: "Draft", description: "Only visible in the admin workspace", tone: "warning" },
  { value: "published", label: "Published", description: "Visible to everyone on the website", tone: "success" },
] as const;

export function AdminConsole({ stats, analytics, initialUsers, initialPosts, initialProjects, initialComments }: { stats: { label: string; value: string; detail: string }[]; analytics: Analytics; initialUsers: AdminUser[]; initialPosts: AdminPost[]; initialProjects: AdminProject[]; initialComments: AdminComment[] }) {
  const [tab, setTab] = useState<Tab>("overview"); const [users, setUsers] = useState(initialUsers); const [posts, setPosts] = useState(initialPosts); const [projects, setProjects] = useState(initialProjects); const [comments, setComments] = useState(initialComments); const [creating, setCreating] = useState(false); const [editingEpisode, setEditingEpisode] = useState<EpisodeInitialData | null>(null); const [loadingEpisodeId, setLoadingEpisodeId] = useState<string | null>(null); const [creatingProject, setCreatingProject] = useState(false); const [message, setMessage] = useState(""); const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null); const [deleteBusy, setDeleteBusy] = useState(false); const [userDetails, setUserDetails] = useState<UserDetails | null>(null); const [loadingUserId, setLoadingUserId] = useState<string | null>(null);

  async function editPost(id: string) { setLoadingEpisodeId(id); setMessage(""); const response = await fetch(`/api/admin/posts/${id}`); const result = await response.json() as { episode?: EpisodeInitialData; message?: string }; setLoadingEpisodeId(null); if (!response.ok || !result.episode) return setMessage(result.message || "The episode could not be loaded."); setEditingEpisode(result.episode); }
  async function updateUser(id: string, status: "active" | "blocked") { const response = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) setUsers((current) => current.map((user) => user.id === id ? { ...user, status } : user)); else setMessage("The member could not be updated."); }
  async function loadUserDetails(id: string) { setLoadingUserId(id); setMessage(""); const response = await fetch(`/api/admin/users/${id}`); const result = await response.json().catch(() => null) as UserDetails & { message?: string } | null; setLoadingUserId(null); if (!response.ok || !result?.member) return setMessage(result?.message || "Member details could not be loaded."); setUserDetails(result); }
  async function executeDelete() { if (!deleteTarget) return; setDeleteBusy(true); const endpoint = deleteTarget.kind === "episode" ? `/api/admin/posts/${deleteTarget.id}` : deleteTarget.kind === "project" ? `/api/admin/projects/${deleteTarget.id}` : deleteTarget.kind === "comment" ? `/api/comments/${deleteTarget.id}` : `/api/admin/users/${deleteTarget.id}`; const response = await fetch(endpoint, { method: "DELETE" }); setDeleteBusy(false); if (!response.ok) return setMessage(`The ${deleteTarget.kind} could not be deleted.`); if (deleteTarget.kind === "episode") setPosts((current) => current.filter((item) => item.id !== deleteTarget.id)); else if (deleteTarget.kind === "project") setProjects((current) => current.filter((item) => item.id !== deleteTarget.id)); else if (deleteTarget.kind === "comment") setComments((current) => current.filter((item) => item.id !== deleteTarget.id)); else setUsers((current) => current.filter((item) => item.id !== deleteTarget.id)); setDeleteTarget(null); setMessage(""); }
  async function createProject(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const fields = Object.fromEntries(new FormData(form)); const body = { ...fields, tech: String(fields.tech).split(",").map((item) => item.trim()).filter(Boolean) }; const response = await fetch("/api/admin/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { id?: string; message?: string }; if (!response.ok || !result.id) return setMessage(result.message || "The project could not be created."); setProjects((current) => [{ id: result.id!, title: String(fields.title), slug: String(fields.slug), status: String(fields.status), previewUrl: String(fields.previewUrl), downloadUrl: String(fields.downloadUrl) }, ...current]); setCreatingProject(false); setMessage(""); form.reset(); }

  const nav = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "analytics", label: "Analytics", icon: BarChart3 }, { id: "episodes", label: "Episodes", icon: FileText }, { id: "projects", label: "Projects", icon: Code2 }, { id: "comments", label: "Comments", icon: MessageSquare }, { id: "users", label: "Members", icon: UsersRound }] as const;
  return <div className="admin-console">
    <aside className="admin-sidebar"><div><span className="admin-shield"><ShieldCheck size={18} /></span><strong>Admin Console</strong></div><nav>{nav.map((item) => <button type="button" className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)} key={item.id}><item.icon size={15} />{item.label}</button>)}</nav></aside>
    <section className="admin-workspace">
      <header className="admin-workspace-head"><div><span className="eyebrow">Private workspace</span><h1>{tab === "overview" ? "Command center" : nav.find((item) => item.id === tab)?.label}</h1></div>{tab === "episodes" ? <button type="button" className="button button-accent" onClick={() => setCreating(true)}><Plus size={15} /> New episode</button> : tab === "projects" ? <button type="button" className="button button-accent" onClick={() => setCreatingProject(true)}><Plus size={15} /> New project</button> : null}</header>
      {message ? <div className="form-message" role="status">{message}</div> : null}
      {tab === "overview" ? <><div className="stats-grid">{stats.map((stat) => <article className="stat-card" key={stat.label}><span>{stat.label}</span><strong>{stat.value}</strong><span className="stat-delta">{stat.detail}</span></article>)}</div><div className="admin-panel admin-welcome"><ShieldCheck size={31} /><div><h2>Your workspace is protected.</h2><p>Create episode hubs, moderate discussions, and manage member access from the navigation on the left.</p></div></div></> : null}
      {tab === "analytics" ? <AnalyticsDashboard analytics={analytics} /> : null}
      {tab === "episodes" ? <AdminTable headings={["Episode", "Slug", "Status", "Actions"]}>{posts.map((post) => <tr key={post.id}><td><strong>{post.title}</strong></td><td><small>/episodes/{post.slug}</small></td><td><span className="status">{post.status}</span></td><td><div className="table-actions"><button className="table-action" type="button" onClick={() => editPost(post.id)} disabled={loadingEpisodeId === post.id}>{loadingEpisodeId === post.id ? <LoaderCircle className="spin" size={13} /> : <Pencil size={13} />} Edit</button><button className="table-action danger" type="button" onClick={() => setDeleteTarget({ kind: "episode", id: post.id, name: post.title })}><Trash2 size={13} /> Delete</button></div></td></tr>)}</AdminTable> : null}
      {tab === "projects" ? <><div className="form-message" style={{ marginBottom: 12 }}>Project files can be uploaded securely to R2 through <code>/api/admin/uploads</code>. Preview and download URLs are stored with each project.</div><AdminTable headings={["Project", "Slug", "Status", "Files", "Actions"]}>{projects.map((project) => <tr key={project.id}><td><strong>{project.title}</strong></td><td><small>/{project.slug}</small></td><td><span className="status">{project.status}</span></td><td><a className="text-link" href={project.previewUrl} target="_blank" rel="noopener noreferrer">Preview</a> · <a className="text-link" href={project.downloadUrl}>Download</a></td><td><button className="table-action danger" type="button" onClick={() => setDeleteTarget({ kind: "project", id: project.id, name: project.title })}><Trash2 size={13} /> Delete</button></td></tr>)}</AdminTable></> : null}
      {tab === "comments" ? <AdminTable headings={["Author", "Comment", "Episode", "Actions"]}>{comments.map((comment) => <tr key={comment.id}><td><strong>{comment.author}</strong></td><td className="truncate-cell">{comment.content}</td><td><small>{comment.post}</small></td><td><button className="table-action danger" type="button" onClick={() => setDeleteTarget({ kind: "comment", id: comment.id, name: `Comment by ${comment.author}` })}><Trash2 size={13} /> Remove</button></td></tr>)}</AdminTable> : null}
      {tab === "users" ? <AdminTable headings={["Member", "Age", "Country", "Status", "Actions"]}>{users.map((user) => <tr key={user.id}><td><strong>{user.name}</strong><small>{user.email}</small></td><td>{user.age ?? "—"}</td><td>{user.country}</td><td><span className="status">{user.status}</span></td><td><div className="table-actions"><button className="table-action" type="button" onClick={() => void loadUserDetails(user.id)} disabled={loadingUserId === user.id}>{loadingUserId === user.id ? <LoaderCircle className="spin" size={13} /> : <Eye size={13} />}Details</button><button className="table-action" type="button" onClick={() => updateUser(user.id, user.status === "blocked" ? "active" : "blocked")}><Ban size={13} />{user.status === "blocked" ? "Unblock" : "Block"}</button><button className="table-action danger" type="button" onClick={() => setDeleteTarget({ kind: "member", id: user.id, name: user.name })}><Trash2 size={13} />Delete</button></div></td></tr>)}</AdminTable> : null}
    </section>
    {creating ? <EpisodeEditor onClose={() => setCreating(false)} onCreated={(post) => { setPosts((current) => [post, ...current]); setMessage(""); }} /> : null}
    {editingEpisode ? <EpisodeEditor initialData={editingEpisode} onClose={() => setEditingEpisode(null)} onCreated={(post) => { setPosts((current) => current.map((item) => item.id === post.id ? post : item)); setEditingEpisode(null); setMessage("Episode changes saved."); }} /> : null}
    {creatingProject ? <div className="admin-dialog-backdrop"><form className="admin-dialog" onSubmit={createProject}><header><div><span className="eyebrow">New release</span><h2>Create a website project</h2></div><button type="button" onClick={() => setCreatingProject(false)} aria-label="Close"><X size={18} /></button></header><div className="field"><label htmlFor="project-title">Title</label><input id="project-title" name="title" required minLength={3} /></div><div className="form-row"><div className="field"><label htmlFor="project-slug">URL slug</label><input id="project-slug" name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></div><div className="field"><label htmlFor="project-tech">Technologies</label><input id="project-tech" name="tech" required placeholder="Next.js, TypeScript, Tailwind" /></div></div><div className="field"><label htmlFor="project-description">Description</label><textarea id="project-description" name="description" required minLength={10} maxLength={400} rows={3} /></div><div className="form-row"><div className="field"><label htmlFor="project-preview">Preview URL</label><input id="project-preview" name="previewUrl" required placeholder="/demos/project.html" /></div><div className="field"><label htmlFor="project-download">Download URL</label><input id="project-download" name="downloadUrl" required placeholder="/downloads/project.zip" /></div></div><div className="field"><label htmlFor="project-status">Status</label><UiSelect id="project-status" name="status" defaultValue="draft" options={publishingOptions} ariaLabel="Project status" /></div><button className="button button-accent" type="submit">Create project</button></form></div> : null}
    <ConfirmDialog open={Boolean(deleteTarget)} title={`Delete ${deleteTarget?.kind || "item"}?`} description={`You are about to delete “${deleteTarget?.name || "this item"}”. This action cannot be undone.`} confirmLabel={`Delete ${deleteTarget?.kind || "item"}`} busy={deleteBusy} onCancel={() => setDeleteTarget(null)} onConfirm={executeDelete} />
    {userDetails ? <UserDetailsDialog details={userDetails} onClose={() => setUserDetails(null)} /> : null}
  </div>;
}

function AdminTable({ headings, children }: { headings: string[]; children: React.ReactNode }) { return <section className="admin-panel"><div className="table-wrap"><table><thead><tr>{headings.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{children}</tbody></table></div></section>; }

function formatDuration(totalSeconds: number) { const hours = Math.floor(totalSeconds / 3600); const minutes = Math.floor((totalSeconds % 3600) / 60); return hours ? `${hours}h ${minutes}m` : `${minutes}m`; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never"; }
function MetricBars({ title, icon, rows, total }: { title: string; icon: React.ReactNode; rows: { label: string; value: number }[]; total: number }) { return <article className="analytics-card"><header><span>{icon}</span><h3>{title}</h3></header>{rows.length ? <div className="metric-bars">{rows.map((row) => <div key={row.label}><div><span>{row.label}</span><strong>{row.value.toLocaleString("en")}</strong></div><i><b style={{ width: `${Math.max(3, (row.value / Math.max(total, 1)) * 100)}%` }} /></i></div>)}</div> : <p className="analytics-empty">No analytics data yet.</p>}</article>; }
function AnalyticsDashboard({ analytics }: { analytics: Analytics }) { return <div className="analytics-dashboard"><div className="analytics-summary"><article><Eye size={18} /><span>Total views</span><strong>{analytics.totalViews.toLocaleString("en")}</strong></article><article><UsersRound size={18} /><span>Unique visitors</span><strong>{analytics.uniqueVisitors.toLocaleString("en")}</strong></article><article><Clock3 size={18} /><span>Time on site</span><strong>{formatDuration(analytics.totalDurationSeconds)}</strong></article></div><div className="analytics-grid"><MetricBars title="Visitor locations" icon={<MapPinned size={18} />} rows={analytics.countries} total={analytics.totalViews} /><MetricBars title="Device types" icon={<MonitorSmartphone size={18} />} rows={analytics.devices} total={analytics.totalViews} /><MetricBars title="Browsers" icon={<Globe2 size={18} />} rows={analytics.browsers} total={analytics.totalViews} /><MetricBars title="Top pages" icon={<Activity size={18} />} rows={analytics.paths} total={analytics.totalViews} /></div></div>; }
function UserDetailsDialog({ details, onClose }: { details: UserDetails; onClose: () => void }) { return <div className="admin-dialog-backdrop"><section className="admin-dialog user-details-dialog" role="dialog" aria-modal="true" aria-labelledby="user-details-title"><header><div><span className="eyebrow">Member intelligence</span><h2 id="user-details-title">{details.member.name}</h2><p>@{details.member.username} · {details.member.email}</p></div><button type="button" onClick={onClose} aria-label="Close member details"><X size={18} /></button></header><div className="user-detail-summary"><article><span>Page views</span><strong>{details.totals.visits}</strong></article><article><span>Time on site</span><strong>{formatDuration(details.totals.durationSeconds)}</strong></article><article><span>Joined</span><strong>{formatDate(details.member.createdAt)}</strong></article><article><span>Last login</span><strong>{formatDate(details.member.lastLoginAt)}</strong></article></div><section className="detail-section"><h3><MonitorSmartphone size={17} /> Known devices</h3>{details.devices.length ? <div className="device-list">{details.devices.map((device) => <article key={device.id}><div><strong>{device.deviceType || "Unknown device"} · {device.operatingSystem || "Unknown OS"}</strong><span>{device.browser || "Unknown browser"} · {device.city || device.region || device.countryCode || "Unknown location"}</span></div><dl><div><dt>IP address</dt><dd>{device.ipAddress}</dd></div><div><dt>Visits</dt><dd>{device.visitCount}</dd></div><div><dt>Time</dt><dd>{formatDuration(device.totalDurationSeconds)}</dd></div><div><dt>Last seen</dt><dd>{formatDate(device.lastSeenAt)}</dd></div></dl></article>)}</div> : <p className="analytics-empty">No known devices.</p>}</section><section className="detail-section"><h3><ShieldCheck size={17} /> Login sessions</h3>{details.sessions.length ? <div className="session-list">{details.sessions.map((session) => <div key={session.id}><span>{session.deviceType || "Device"} · {session.browser || "Browser"}</span><strong>{session.ipAddress}</strong><small>{session.city || session.region || session.countryCode || "Unknown location"} · {formatDate(session.createdAt)}</small></div>)}</div> : <p className="analytics-empty">No active login sessions.</p>}</section><section className="detail-section"><h3><Activity size={17} /> Recent page views</h3>{details.recentVisits.length ? <div className="visit-list">{details.recentVisits.map((visit) => <div key={visit.id}><code>{visit.path}</code><span>{visit.deviceType || "Device"} · {visit.browser || "Browser"}</span><strong>{formatDuration(visit.durationSeconds)}</strong><small>{formatDate(visit.createdAt)}</small></div>)}</div> : <p className="analytics-empty">No consented page views.</p>}</section></section></div>; }
