"use client";

import { Activity, Ban, BarChart3, Clock3, Code2, Eye, FileText, Globe2, LayoutDashboard, LoaderCircle, MapPinned, MessageSquare, MonitorSmartphone, Pencil, Plus, Search, ShieldCheck, Trash2, UsersRound } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { AdminPortal } from "./admin-portal";
import { EpisodeEditor, type EpisodeInitialData } from "./episode-editor";
import { ProjectEditor, type ProjectDetails } from "./project-editor";
import { ConfirmDialog } from "./confirm-dialog";
import { MemberDetailsDialog } from "./member-details-dialog";
import { MemberRoleEditor } from "./member-role-editor";
import { effectiveAdminPermissions, type AdminPermission } from "@/lib/admin-permissions";
import { countryName } from "@/lib/location";

type AdminUser = { id: string; name: string; username: string; email: string; country: string; declaredCountryCode: string | null; status: string; role: string; adminPermissions: string[] | null; createdAt: string; lastLoginAt: string | null; emailVerifiedAt: string | null };
type AdminPost = { id: string; title: string; slug: string; status: string };
type AdminComment = { id: string; content: string; author: string; post: string };
type AdminProject = { id: string; title: string; slug: string; status: string; previewUrl: string; downloadUrl: string };
type ActivityEntry = { id: string; action: string; targetType: string; targetId: string | null; createdAt: string };
type Analytics = { totalViews: number; uniqueVisitors: number; totalDurationSeconds: number; countries: { label: string; value: number }[]; devices: { label: string; value: number }[]; browsers: { label: string; value: number }[]; paths: { label: string; value: number }[] };
export type UserDetails = { member: AdminUser & { bio: string | null; birthDate: string | null }; totals: { visits: number; durationSeconds: number; comments: number }; devices: { id: string; countryCode: string | null; city: string | null; region: string | null; deviceType: string | null; operatingSystem: string | null; browser: string | null; ipAddress: string; visitCount: number; totalDurationSeconds: number; createdAt: string; lastSeenAt: string }[]; sessions: { id: string; countryCode: string | null; city: string | null; region: string | null; deviceType: string | null; operatingSystem: string | null; browser: string | null; ipAddress: string; createdAt: string; lastSeenAt: string; expiresAt: string }[]; recentVisits: { id: string; path: string; countryCode: string | null; city: string | null; deviceType: string | null; browser: string | null; durationSeconds: number; createdAt: string }[]; recentComments: { id: string; content: string; postTitle: string; postSlug: string; createdAt: string }[] };
type DeleteTarget = { kind: "episode" | "project" | "comment" | "member"; id: string; name: string };
type Tab = "overview" | "analytics" | "episodes" | "projects" | "comments" | "users";

export function AdminConsole({ stats, analytics, initialUsers, initialPosts, initialProjects, initialComments, initialActivity = [], adminId = "", adminPermissions = [] }: { stats: { label: string; value: string; detail: string }[]; analytics: Analytics; initialUsers: AdminUser[]; initialPosts: AdminPost[]; initialProjects: AdminProject[]; initialComments: AdminComment[]; initialActivity?: ActivityEntry[]; adminId?: string; adminPermissions?: AdminPermission[] }) {
  const router = useRouter();
  const [tab, setTab] = useState<Tab>("overview"); const [users, setUsers] = useState(initialUsers); const [posts, setPosts] = useState(initialPosts); const [projects, setProjects] = useState(initialProjects); const [removedCommentIds, setRemovedCommentIds] = useState<string[]>([]); const [creating, setCreating] = useState(false); const [editingEpisode, setEditingEpisode] = useState<EpisodeInitialData | null>(null); const [loadingEpisodeId, setLoadingEpisodeId] = useState<string | null>(null); const [projectEditor, setProjectEditor] = useState<ProjectDetails | "new" | null>(null); const [loadingProjectId, setLoadingProjectId] = useState<string | null>(null); const [message, setMessage] = useState(""); const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null); const [deleteBusy, setDeleteBusy] = useState(false); const [userDetails, setUserDetails] = useState<UserDetails | null>(null); const [roleMember, setRoleMember] = useState<AdminUser | null>(null); const [loadingUserId, setLoadingUserId] = useState<string | null>(null); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState("all");
  const comments = initialComments.filter((comment) => !removedCommentIds.includes(comment.id));
  const can = (permission: AdminPermission) => adminPermissions.includes(permission);
  const canManageMember = (member: AdminUser) => member.role !== "admin" || (can("members.roles") && effectiveAdminPermissions(member).every((permission) => can(permission)));
  function changeTab(next: Tab) { setTab(next); setSearch(""); setStatusFilter("all"); setMessage(""); }

  async function editPost(id: string) { setLoadingEpisodeId(id); setMessage(""); const response = await fetch(`/api/admin/posts/${id}`); const result = await response.json() as { episode?: EpisodeInitialData; message?: string }; setLoadingEpisodeId(null); if (!response.ok || !result.episode) return setMessage(result.message || "The episode could not be loaded."); setEditingEpisode(result.episode); }
  async function editProject(id: string) { setLoadingProjectId(id); setMessage(""); try { const response = await fetch(`/api/admin/projects/${id}`); const result = await response.json() as { project?: ProjectDetails; message?: string }; if (!response.ok || !result.project) throw new Error(result.message || "The project could not be loaded."); setProjectEditor(result.project); } catch (error) { setMessage(error instanceof Error ? error.message : "The project could not be loaded."); } finally { setLoadingProjectId(null); } }
  function projectSaved(project: ProjectDetails) { setProjects((current) => current.some((item) => item.id === project.id) ? current.map((item) => item.id === project.id ? project : item) : [project, ...current]); setProjectEditor(null); setMessage("Project saved."); router.refresh(); }
  async function updateUser(id: string, status: "active" | "blocked") { const response = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) setUsers((current) => current.map((user) => user.id === id ? { ...user, status } : user)); else setMessage("The member could not be updated."); }
  async function loadUserDetails(id: string) { setLoadingUserId(id); setMessage(""); const response = await fetch(`/api/admin/users/${id}`); const result = await response.json().catch(() => null) as UserDetails & { message?: string } | null; setLoadingUserId(null); if (!response.ok || !result?.member) return setMessage(result?.message || "Member details could not be loaded."); setUserDetails(result); }
  async function executeDelete() {
    if (!deleteTarget || deleteBusy) return;
    const target = deleteTarget;
    setDeleteBusy(true);
    setMessage("");
    const endpoint = target.kind === "episode" ? `/api/admin/posts/${target.id}` : target.kind === "project" ? `/api/admin/projects/${target.id}` : target.kind === "comment" ? `/api/comments/${target.id}` : `/api/admin/users/${target.id}`;
    try {
      const response = await fetch(endpoint, { method: "DELETE" });
      const result = await response.json().catch(() => null) as { message?: string } | null;
      if (!response.ok) throw new Error(result?.message || `The ${target.kind} could not be deleted.`);
      if (target.kind === "episode") setPosts((current) => current.filter((item) => item.id !== target.id));
      else if (target.kind === "project") setProjects((current) => current.filter((item) => item.id !== target.id));
      else if (target.kind === "comment") setRemovedCommentIds((current) => [...current, target.id]);
      else {
        setUsers((current) => current.filter((item) => item.id !== target.id));
        setUserDetails((current) => current?.member.id === target.id ? null : current);
        setRoleMember((current) => current?.id === target.id ? null : current);
      }
      setDeleteTarget(null);
      router.refresh();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : `The ${target.kind} could not be deleted.`);
    } finally {
      setDeleteBusy(false);
    }
  }
  async function revokeSessions(id: string) { const response = await fetch(`/api/admin/users/${id}/sessions`, { method: "DELETE" }); const result = await response.json() as { revoked?: number; message?: string }; if (!response.ok) throw new Error(result.message || "Login sessions could not be revoked."); setUserDetails((current) => current?.member.id === id ? { ...current, sessions: [] } : current); setMessage(`${result.revoked || 0} login sessions revoked.`); if (id === adminId) { setUserDetails(null); router.replace("/login"); router.refresh(); } }
  function roleSaved(role: "user" | "admin", permissions: string[] | null) { if (!roleMember) return; setUsers((current) => current.map((member) => member.id === roleMember.id ? { ...member, role, adminPermissions: permissions } : member)); setRoleMember(null); setMessage("Member access updated. Their existing sessions were signed out."); router.refresh(); }

  const query = search.trim().toLowerCase();
  const matches = (...values: (string | number | null | undefined)[]) => !query || values.some((value) => String(value ?? "").toLowerCase().includes(query));
  const visiblePosts = posts.filter((post) => matches(post.title, post.slug) && (statusFilter === "all" || post.status === statusFilter));
  const visibleProjects = projects.filter((project) => matches(project.title, project.slug, project.previewUrl) && (statusFilter === "all" || project.status === statusFilter));
  const visibleComments = comments.filter((comment) => matches(comment.author, comment.content, comment.post));
  const visibleUsers = users.filter((user) => matches(user.name, user.username, user.email, countryName(user.declaredCountryCode), countryName(user.country), user.role) && (statusFilter === "all" || user.status === statusFilter));
  const [shown, loaded] = tab === "episodes" ? [visiblePosts.length, posts.length] : tab === "projects" ? [visibleProjects.length, projects.length] : tab === "comments" ? [visibleComments.length, comments.length] : [visibleUsers.length, users.length];
  const searchable = tab === "episodes" || tab === "projects" || tab === "comments" || tab === "users";

  const nav = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, ...(can("analytics.view") ? [{ id: "analytics", label: "Analytics", icon: BarChart3 }] : []), ...(adminPermissions.some((permission) => permission.startsWith("episodes.")) ? [{ id: "episodes", label: "Episodes", icon: FileText }] : []), ...(adminPermissions.some((permission) => permission.startsWith("projects.")) ? [{ id: "projects", label: "Projects", icon: Code2 }] : []), ...(can("comments.delete") ? [{ id: "comments", label: "Comments", icon: MessageSquare }] : []), ...(can("members.view") ? [{ id: "users", label: "Members", icon: UsersRound }] : [])] as { id: Tab; label: string; icon: typeof LayoutDashboard }[];
  return <div className="admin-console">
    <aside className="admin-sidebar"><div><span className="admin-shield"><ShieldCheck size={18} /></span><strong>Admin Console</strong></div><nav aria-label="Admin sections">{nav.map((item) => <button type="button" className={tab === item.id ? "active" : ""} onClick={() => changeTab(item.id)} key={item.id}><item.icon size={15} />{item.label}</button>)}</nav></aside>
    <section className="admin-workspace">
      <header className="admin-workspace-head"><div><span className="eyebrow">Private workspace</span><h1>{tab === "overview" ? "Command center" : nav.find((item) => item.id === tab)?.label}</h1></div>{tab === "episodes" && can("episodes.create") ? <button type="button" className="button button-accent" onClick={() => setCreating(true)}><Plus size={15} /> New episode</button> : tab === "projects" && can("projects.create") ? <button type="button" className="button button-accent" onClick={() => setProjectEditor("new")}><Plus size={15} /> New project</button> : null}</header>
      {message ? <div className="form-message" role="status">{message}</div> : null}
      {tab === "overview" ? <><div className="stats-grid">{stats.map((stat) => <article className="stat-card" key={stat.label}><span>{stat.label}</span><strong>{stat.value}</strong><span className="stat-delta">{stat.detail}</span></article>)}</div><div className="admin-quick-actions">{nav.filter((item) => item.id === "episodes" || item.id === "projects" || item.id === "users").map((item) => <button key={item.id} type="button" onClick={() => changeTab(item.id)}><item.icon size={17} /> Manage {item.label.toLowerCase()}</button>)}</div><div className="admin-panel admin-activity"><header><Activity size={18} /><div><h2>Recent admin activity</h2><p>Content and member access changes are recorded here.</p></div></header>{initialActivity.length ? <ol>{initialActivity.map((entry) => <li key={entry.id}><span className="admin-activity-dot" /><div><strong>{entry.action.replaceAll(".", " ")}</strong><small>{entry.targetType}{entry.targetId ? ` · ${entry.targetId.slice(0, 8)}` : ""}</small></div><time dateTime={entry.createdAt}>{formatDate(entry.createdAt)}</time></li>)}</ol> : <p className="analytics-empty">No admin changes recorded yet.</p>}</div></> : null}
      {tab === "analytics" ? <AnalyticsDashboard analytics={analytics} /> : null}
      {searchable ? <div className="admin-list-toolbar"><label className="admin-search"><Search size={16} aria-hidden="true" /><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${tab}…`} aria-label={`Search ${tab}`} /></label>{tab !== "comments" ? <div className="admin-filter" role="group" aria-label="Filter by status">{(tab === "users" ? ["all", "active", "blocked"] : ["all", "draft", "published"]).map((filter) => <button type="button" key={filter} className={statusFilter === filter ? "active" : ""} aria-pressed={statusFilter === filter} onClick={() => setStatusFilter(filter)}>{filter}</button>)}</div> : null}<span className="admin-result-count">Showing {shown} of {loaded} loaded</span></div> : null}
      {tab === "episodes" ? <AdminTable headings={["Episode", "Slug", "Status", "Actions"]}>{visiblePosts.length ? visiblePosts.map((post) => <tr key={post.id}><td><strong>{post.title}</strong></td><td><small>/episodes/{post.slug}</small></td><td><span className="status">{post.status}</span></td><td><div className="table-actions">{can("episodes.edit") ? <button className="table-action" type="button" onClick={() => void editPost(post.id)} disabled={loadingEpisodeId === post.id}>{loadingEpisodeId === post.id ? <LoaderCircle className="spin" size={13} /> : <Pencil size={13} />} Edit</button> : null}{can("episodes.delete") ? <button className="table-action danger" type="button" onClick={() => setDeleteTarget({ kind: "episode", id: post.id, name: post.title })}><Trash2 size={13} /> Delete</button> : null}</div></td></tr>) : <EmptyRow columns={4} />}</AdminTable> : null}
      {tab === "projects" ? <AdminTable headings={["Project", "Slug", "Status", "Files", "Actions"]}>{visibleProjects.length ? visibleProjects.map((project) => <tr key={project.id}><td><strong>{project.title}</strong></td><td><small>/{project.slug}</small></td><td><span className="status">{project.status}</span></td><td><a className="text-link" href={project.previewUrl} target="_blank" rel="noopener noreferrer">Preview</a> · <a className="text-link" href={project.downloadUrl}>Download</a></td><td><div className="table-actions">{can("projects.edit") ? <button className="table-action" type="button" onClick={() => void editProject(project.id)} disabled={loadingProjectId === project.id}>{loadingProjectId === project.id ? <LoaderCircle className="spin" size={13} /> : <Pencil size={13} />} Edit</button> : null}{can("projects.delete") ? <button className="table-action danger" type="button" onClick={() => setDeleteTarget({ kind: "project", id: project.id, name: project.title })}><Trash2 size={13} /> Delete</button> : null}</div></td></tr>) : <EmptyRow columns={5} />}</AdminTable> : null}
      {tab === "comments" ? <AdminTable headings={["Author", "Comment", "Episode", "Actions"]}>{visibleComments.length ? visibleComments.map((comment) => <tr key={comment.id}><td><strong>{comment.author}</strong></td><td className="truncate-cell">{comment.content}</td><td><small>{comment.post}</small></td><td>{can("comments.delete") ? <button className="table-action danger" type="button" onClick={() => setDeleteTarget({ kind: "comment", id: comment.id, name: `Comment by ${comment.author}` })}><Trash2 size={13} /> Remove</button> : null}</td></tr>) : <EmptyRow columns={4} />}</AdminTable> : null}
      {tab === "users" ? <AdminTable headings={["Member", "Country", "Joined / last login", "Role", "Status", "Actions"]}>{visibleUsers.length ? visibleUsers.map((user) => <tr key={user.id}><td><strong>{user.name}</strong><small>@{user.username} · {user.email}</small></td><td><strong>{countryName(user.declaredCountryCode || user.country)}</strong><small>{user.declaredCountryCode ? "Selected by member" : "Detected from connection"}</small>{user.declaredCountryCode && user.country && user.declaredCountryCode !== user.country ? <small>Connection: {countryName(user.country)}</small> : null}</td><td><small>Joined {formatDate(user.createdAt)}</small><small>Login {formatDate(user.lastLoginAt)}</small></td><td><span className="status">{user.role}</span></td><td><span className="status">{user.status}</span><small>{user.emailVerifiedAt ? "Email verified" : "Email unverified"}</small></td><td><div className="table-actions"><button className="table-action" type="button" onClick={() => void loadUserDetails(user.id)} disabled={loadingUserId === user.id}>{loadingUserId === user.id ? <LoaderCircle className="spin" size={13} /> : <Eye size={13} />} Details</button>{can("members.roles") && canManageMember(user) && user.id !== adminId && user.status === "active" ? <button className="table-action" type="button" onClick={() => setRoleMember(user)}><Pencil size={13} /> Access</button> : null}{can("members.block") ? <button className="table-action" type="button" onClick={() => void updateUser(user.id, user.status === "blocked" ? "active" : "blocked")} disabled={user.id === adminId || user.status === "deleted" || !canManageMember(user)}><Ban size={13} />{user.status === "blocked" ? "Unblock" : "Block"}</button> : null}{can("members.delete") ? <button className="table-action danger" type="button" onClick={() => setDeleteTarget({ kind: "member", id: user.id, name: user.name })} disabled={user.id === adminId || user.status === "deleted" || !canManageMember(user)}><Trash2 size={13} /> Delete</button> : null}</div></td></tr>) : <EmptyRow columns={6} />}</AdminTable> : null}
    </section>
    {creating ? <AdminPortal><EpisodeEditor onClose={() => setCreating(false)} onCreated={(post) => { setPosts((current) => [post, ...current]); setCreating(false); setMessage("Episode created."); router.refresh(); }} /></AdminPortal> : null}
    {editingEpisode ? <AdminPortal><EpisodeEditor initialData={editingEpisode} onClose={() => setEditingEpisode(null)} onCreated={(post) => { setPosts((current) => current.map((item) => item.id === post.id ? post : item)); setEditingEpisode(null); setMessage("Episode changes saved."); router.refresh(); }} /></AdminPortal> : null}
    {projectEditor ? <AdminPortal><ProjectEditor key={projectEditor === "new" ? "new" : projectEditor.id} project={projectEditor === "new" ? undefined : projectEditor} onClose={() => setProjectEditor(null)} onSaved={projectSaved} /></AdminPortal> : null}
    <ConfirmDialog open={Boolean(deleteTarget)} title={`Delete ${deleteTarget?.kind || "item"}?`} description={deleteTarget?.kind === "member" ? `Permanently delete “${deleteTarget.name}” and their account data, comments and comment threads. Their episodes will remain on the site. This action cannot be undone.` : `You are about to delete “${deleteTarget?.name || "this item"}”. This action cannot be undone.`} confirmLabel={`Delete ${deleteTarget?.kind || "item"}`} busy={deleteBusy} onCancel={() => setDeleteTarget(null)} onConfirm={executeDelete} />
    {userDetails ? <AdminPortal><MemberDetailsDialog details={userDetails} canRevoke={can("members.sessions")} onClose={() => setUserDetails(null)} onRevoke={() => revokeSessions(userDetails.member.id)} /></AdminPortal> : null}
    {roleMember ? <AdminPortal><MemberRoleEditor member={roleMember} actorPermissions={adminPermissions} onClose={() => setRoleMember(null)} onSaved={roleSaved} /></AdminPortal> : null}
  </div>;
}

function AdminTable({ headings, children }: { headings: string[]; children: React.ReactNode }) { return <section className="admin-panel"><div className="table-wrap"><table><thead><tr>{headings.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{children}</tbody></table></div></section>; }
function EmptyRow({ columns }: { columns: number }) { return <tr><td colSpan={columns} className="admin-empty-row">No matching records in the loaded list.</td></tr>; }

function formatDuration(totalSeconds: number) { const hours = Math.floor(totalSeconds / 3600); const minutes = Math.floor((totalSeconds % 3600) / 60); return hours ? `${hours}h ${minutes}m` : `${minutes}m`; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never"; }
function MetricBars({ title, icon, rows, total }: { title: string; icon: React.ReactNode; rows: { label: string; value: number }[]; total: number }) { return <article className="analytics-card"><header><span>{icon}</span><h3>{title}</h3></header>{rows.length ? <div className="metric-bars">{rows.map((row) => <div key={row.label}><div><span>{row.label}</span><strong>{row.value.toLocaleString("en")}</strong></div><i><b style={{ width: `${Math.max(3, (row.value / Math.max(total, 1)) * 100)}%` }} /></i></div>)}</div> : <p className="analytics-empty">No analytics data yet.</p>}</article>; }
function AnalyticsDashboard({ analytics }: { analytics: Analytics }) { return <div className="analytics-dashboard"><div className="analytics-summary"><article><Eye size={18} /><span>Total views</span><strong>{analytics.totalViews.toLocaleString("en")}</strong></article><article><UsersRound size={18} /><span>Unique visitors</span><strong>{analytics.uniqueVisitors.toLocaleString("en")}</strong></article><article><Clock3 size={18} /><span>Time on site</span><strong>{formatDuration(analytics.totalDurationSeconds)}</strong></article></div><div className="analytics-grid"><MetricBars title="Visitor locations" icon={<MapPinned size={18} />} rows={analytics.countries} total={analytics.totalViews} /><MetricBars title="Device types" icon={<MonitorSmartphone size={18} />} rows={analytics.devices} total={analytics.totalViews} /><MetricBars title="Browsers" icon={<Globe2 size={18} />} rows={analytics.browsers} total={analytics.totalViews} /><MetricBars title="Top pages" icon={<Activity size={18} />} rows={analytics.paths} total={analytics.totalViews} /></div></div>; }
